// Data genererad via gAIa från AviList v2025-11Jun-extended.xlsx
// Ordningen följer strikt global taxonomi.
const SPECIES_DATABASE = [
  { id: "knolsvan", name: "Knölsvan", order: 1 },
  { id: "mindre-sangsvan", name: "Mindre sångsvan", order: 2 },
  { id: "sangsvan", name: "Sångsvan", order: 3 },
  { id: "prutgas", name: "Prutgås", order: 4 },
  { id: "rodhalsad-gas", name: "Rödhalsad gås", order: 5 },
  { id: "kanadagas", name: "Kanadagås", order: 6 },
  { id: "vitkindad-gas", name: "Vitkindad gås", order: 7 },
  { id: "stripgas", name: "Stripgås", order: 8 },
  { id: "gragas", name: "Grågås", order: 9 },
  { id: "fjallgas", name: "Fjällgås", order: 10 },
  { id: "blasgas", name: "Bläsgås", order: 11 },
  { id: "spetsbergsgas", name: "Spetsbergsgås", order: 12 },
  { id: "skogsgas", name: "Skogsgås", order: 13 },
  { id: "gravand", name: "Gravand", order: 14 },
  { id: "rostand", name: "Rostand", order: 15 },
  { id: "alfagel", name: "Alfågel", order: 16 },
  { id: "alforradare", name: "Alförrädare", order: 17 },
  { id: "praktejder", name: "Praktejder", order: 18 },
  { id: "ejder", name: "Ejder", order: 19 },
  { id: "sjoorre", name: "Sjöorre", order: 20 },
  { id: "svarta", name: "Svärta", order: 21 },
  { id: "knipa", name: "Knipa", order: 22 },
  { id: "salskrake", name: "Salskrake", order: 23 },
  { id: "smaskrake", name: "Småskrake", order: 24 },
  { id: "storskrake", name: "Storskrake", order: 25 },
  { id: "brunand", name: "Brunand", order: 26 },
  { id: "vigg", name: "Vigg", order: 27 },
  { id: "bergand", name: "Bergand", order: 28 },
  { id: "arta", name: "Årta", order: 29 },
  { id: "skedand", name: "Skedand", order: 30 },
  { id: "snatterand", name: "Snatterand", order: 31 },
  { id: "blasand", name: "Bläsand", order: 32 },
  { id: "grasand", name: "Gräsand", order: 33 },
  { id: "stjartand", name: "Stjärtand", order: 34 },
  { id: "kricka", name: "Kricka", order: 35 },
  { id: "jarpe", name: "Järpe", order: 36 },
  { id: "fjallripa", name: "Fjällripa", order: 37 },
  { id: "dalripa", name: "Dalripa", order: 38 },
  { id: "tjader", name: "Tjäder", order: 39 },
  { id: "orre", name: "Orre", order: 40 },
  { id: "rapphona", name: "Rapphöna", order: 41 },
  { id: "fasan", name: "Fasan", order: 42 },
  { id: "vaktel", name: "Vaktel", order: 43 },
  { id: "smadopping", name: "Smådopping", order: 44 },
  { id: "svarthakedopping", name: "Svarthakedopping", order: 45 },
  { id: "grahakedopping", name: "Gråhakedopping", order: 46 },
  { id: "skaggdopping", name: "Skäggdopping", order: 47 },
  { id: "svarthalsad-dopping", name: "Svarthalsad dopping", order: 48 },
  { id: "gok", name: "Gök", order: 49 },
  { id: "turturduva", name: "Turturduva", order: 50 },
  { id: "turkduva", name: "Turkduva", order: 51 },
  { id: "ringduva", name: "Ringduva", order: 52 },
  { id: "klippduva-tamduva", name: "Klippduva (tamduva)", order: 53 },
  { id: "skogsduva", name: "Skogsduva", order: 54 },
  { id: "trana", name: "Trana", order: 55 },
  { id: "vattenrall", name: "Vattenrall", order: 56 },
  { id: "kornknarr", name: "Kornknarr", order: 57 },
  { id: "rorhona", name: "Rörhöna", order: 58 },
  { id: "sothona", name: "Sothöna", order: 59 },
  { id: "smaflackig-sumphona", name: "Småfläckig sumphöna", order: 60 },
  { id: "skarflacka", name: "Skärfläcka", order: 61 },
  { id: "strandskata", name: "Strandskata", order: 62 },
  { id: "kustpipare", name: "Kustpipare", order: 63 },
  { id: "ljungpipare", name: "Ljungpipare", order: 64 },
  { id: "fjallpipare", name: "Fjällpipare", order: 65 },
  { id: "storre-strandpipare", name: "Större strandpipare", order: 66 },
  { id: "tofsvipa", name: "Tofsvipa", order: 67 },
  { id: "smaspov", name: "Småspov", order: 68 },
  { id: "storspov", name: "Storspov", order: 69 },
  { id: "myrspov", name: "Myrspov", order: 70 },
  { id: "rodspov", name: "Rödspov", order: 71 },
  { id: "dvargbeckasin", name: "Dvärgbeckasin", order: 72 },
  { id: "morkulla", name: "Morkulla", order: 73 },
  { id: "dubbelbeckasin", name: "Dubbelbeckasin", order: 74 },
  { id: "enkelbeckasin", name: "Enkelbeckasin", order: 75 },
  { id: "drillsnappa", name: "Drillsnäppa", order: 76 },
  { id: "brednabbad-simsnappa", name: "Brednäbbad simsnäppa", order: 77 },
  { id: "smalsnappa", name: "Smalsnäppa", order: 78 },
  { id: "skogssnappa", name: "Skogssnäppa", order: 79 },
  { id: "dammsnappa", name: "Dammsnäppa", order: 80 },
  { id: "gronbena", name: "Grönbena", order: 81 },
  { id: "rodbena", name: "Rödbena", order: 82 },
  { id: "svartsnappa", name: "Svartsnäppa", order: 83 },
  { id: "gluttsnappa", name: "Gluttsnäppa", order: 84 },
  { id: "roskarl", name: "Roskarl", order: 85 },
  { id: "kustsnappa", name: "Kustsnäppa", order: 86 },
  { id: "brushane", name: "Brushane", order: 87 },
  { id: "myrsnappa", name: "Myrsnäppa", order: 88 },
  { id: "spovsnappa", name: "Spovsnäppa", order: 89 },
  { id: "mosnappa", name: "Mosnäppa", order: 90 },
  { id: "sandlopare", name: "Sandlöpare", order: 91 },
  { id: "karrsnappa", name: "Kärrsnäppa", order: 92 },
  { id: "skarsnappa", name: "Skärsnäppa", order: 93 },
  { id: "tuvsnappa", name: "Tuvsnäppa", order: 94 },
  { id: "smasnappa", name: "Småsnäppa", order: 95 },
  { id: "kustlabb", name: "Kustlabb", order: 96 },
  { id: "fjallabb", name: "Fjällabb", order: 97 },
  { id: "bredstjartad-labb", name: "Bredstjärtad labb", order: 98 },
  { id: "storlabb", name: "Storlabb", order: 99 },
  { id: "lunnefagel", name: "Lunnefågel", order: 100 },
  { id: "tobisgrissla", name: "Tobisgrissla", order: 101 },
  { id: "tordmule", name: "Tordmule", order: 102 },
  { id: "alkekung", name: "Alkekung", order: 103 },
  { id: "sillgrissla", name: "Sillgrissla", order: 104 },
  { id: "smatarna", name: "Småtärna", order: 105 },
  { id: "skrantarna", name: "Skräntärna", order: 106 },
  { id: "vitvingad-tarna", name: "Vitvingad tärna", order: 107 },
  { id: "svarttarna", name: "Svarttärna", order: 108 },
  { id: "kentsk-tarna", name: "Kentsk tärna", order: 109 },
  { id: "silvertarna", name: "Silvertärna", order: 110 },
  { id: "fisktarna", name: "Fisktärna", order: 111 },
  { id: "dvargmas", name: "Dvärgmås", order: 112 },
  { id: "tretaig-mas", name: "Tretåig mås", order: 113 },
  { id: "tarnmas", name: "Tärnmås", order: 114 },
  { id: "skrattmas", name: "Skrattmås", order: 115 },
  { id: "svarthuvad-mas", name: "Svarthuvad mås", order: 116 },
  { id: "fiskmas", name: "Fiskmås", order: 117 },
  { id: "kaspisk-trut", name: "Kaspisk trut", order: 118 },
  { id: "gratrut", name: "Gråtrut", order: 119 },
  { id: "medelhavstrut", name: "Medelhavstrut", order: 120 },
  { id: "havstrut", name: "Havstrut", order: 121 },
  { id: "vittrut", name: "Vittrut", order: 122 },
  { id: "silltrut", name: "Silltrut", order: 123 },
  { id: "vitvingad-trut", name: "Vitvingad trut", order: 124 },
  { id: "smalom", name: "Smålom", order: 125 },
  { id: "svartnabbad-islom", name: "Svartnäbbad islom", order: 126 },
  { id: "vitnabbad-islom", name: "Vitnäbbad islom", order: 127 },
  { id: "storlom", name: "Storlom", order: 128 },
  { id: "klykstjartad-stormsvala", name: "Klykstjärtad stormsvala", order: 129 },
  { id: "stormfagel", name: "Stormfågel", order: 130 },
  { id: "mindre-lira", name: "Mindre lira", order: 131 },
  { id: "svart-stork", name: "Svart stork", order: 132 },
  { id: "vit-stork", name: "Vit stork", order: 133 },
  { id: "havssula", name: "Havssula", order: 134 },
  { id: "toppskarv", name: "Toppskarv", order: 135 },
  { id: "storskarv", name: "Storskarv", order: 136 },
  { id: "rordrom", name: "Rördrom", order: 137 },
  { id: "silkeshager", name: "Silkeshäger", order: 138 },
  { id: "agretthager", name: "Ägretthäger", order: 139 },
  { id: "grahager", name: "Gråhäger", order: 140 },
  { id: "nattskarra", name: "Nattskärra", order: 141 },
  { id: "tornseglare", name: "Tornseglare", order: 142 },
  { id: "parlugla", name: "Pärlugla", order: 143 },
  { id: "hokuggla", name: "Hökuggla", order: 144 },
  { id: "sparvuggla", name: "Sparvuggla", order: 145 },
  { id: "jorduggla", name: "Jorduggla", order: 146 },
  { id: "hornuggla", name: "Hornuggla", order: 147 },
  { id: "berguv", name: "Berguv", order: 148 },
  { id: "kattuggla", name: "Kattuggla", order: 149 },
  { id: "slaguggla", name: "Slaguggla", order: 150 },
  { id: "lappuggla", name: "Lappuggla", order: 151 },
  { id: "fiskgjuse", name: "Fiskgjuse", order: 152 },
  { id: "bivrak", name: "Bivråk", order: 153 },
  { id: "kungsorn", name: "Kungsörn", order: 154 },
  { id: "sparvhok", name: "Sparvhök", order: 155 },
  { id: "duvhok", name: "Duvhök", order: 156 },
  { id: "bla-karrhok", name: "Blå kärrhök", order: 157 },
  { id: "angshok", name: "Ängshök", order: 158 },
  { id: "brun-karrhok", name: "Brun kärrhök", order: 159 },
  { id: "rod-glada", name: "Röd glada", order: 160 },
  { id: "brun-glada", name: "Brun glada", order: 161 },
  { id: "havsorn", name: "Havsörn", order: 162 },
  { id: "fjallvrak", name: "Fjällvråk", order: 163 },
  { id: "ormvrak", name: "Ormvråk", order: 164 },
  { id: "harfagel", name: "Härfågel", order: 165 },
  { id: "biatare", name: "Biätare", order: 166 },
  { id: "kungsfiskare", name: "Kungsfiskare", order: 167 },
  { id: "goktyta", name: "Göktyta", order: 168 },
  { id: "graspett", name: "Gråspett", order: 169 },
  { id: "grongoling", name: "Gröngöling", order: 170 },
  { id: "spillkraka", name: "Spillkråka", order: 171 },
  { id: "tretaig-hackspett", name: "Tretåig hackspett", order: 172 },
  { id: "vitryggig-hackspett", name: "Vitryggig hackspett", order: 173 },
  { id: "storre-hackspett", name: "Större hackspett", order: 174 },
  { id: "mindre-hackspett", name: "Mindre hackspett", order: 175 },
  { id: "tornfalk", name: "Tornfalk", order: 176 },
  { id: "aftonfalk", name: "Aftonfalk", order: 177 },
  { id: "stenfalk", name: "Stenfalk", order: 178 },
  { id: "larkfalk", name: "Lärkfalk", order: 179 },
  { id: "pilgrimsfalk", name: "Pilgrimsfalk", order: 180 },
  { id: "jaktfalk", name: "Jaktfalk", order: 181 },
  { id: "sommargylling", name: "Sommargylling", order: 182 },
  { id: "varfagel", name: "Varfågel", order: 183 },
  { id: "tornskata", name: "Törnskata", order: 184 },
  { id: "lavskrika", name: "Lavskrika", order: 185 },
  { id: "notskrika", name: "Nötskrika", order: 186 },
  { id: "skata", name: "Skata", order: 187 },
  { id: "notkraka", name: "Nötkråka", order: 188 },
  { id: "kaja", name: "Kaja", order: 189 },
  { id: "raka", name: "Råka", order: 190 },
  { id: "korp", name: "Korp", order: 191 },
  { id: "grakraka", name: "Gråkråka", order: 192 },
  { id: "pungmes", name: "Pungmes", order: 193 },
  { id: "blames", name: "Blåmes", order: 194 },
  { id: "talgoxe", name: "Talgoxe", order: 195 },
  { id: "svartmes", name: "Svartmes", order: 196 },
  { id: "tofsmes", name: "Tofsmes", order: 197 },
  { id: "entita", name: "Entita", order: 198 },
  { id: "talltita", name: "Talltita", order: 199 },
  { id: "lappmes", name: "Lappmes", order: 200 },
  { id: "skaggmes", name: "Skäggmes", order: 201 },
  { id: "tradlarka", name: "Trädlärka", order: 202 },
  { id: "sanglarka", name: "Sånglärka", order: 203 },
  { id: "tofslarka", name: "Tofslärka", order: 204 },
  { id: "berglarka", name: "Berglärka", order: 205 },
  { id: "harmsangare", name: "Härmsångare", order: 206 },
  { id: "savsangare", name: "Sävsångare", order: 207 },
  { id: "busksangare", name: "Busksångare", order: 208 },
  { id: "karrsangare", name: "Kärrsångare", order: 209 },
  { id: "rorsangare", name: "Rörsångare", order: 210 },
  { id: "trastsangare", name: "Trastsångare", order: 211 },
  { id: "flodsangare", name: "Flodsångare", order: 212 },
  { id: "vassangare", name: "Vassångare", order: 213 },
  { id: "grashoppsangare", name: "Gräshoppsångare", order: 214 },
  { id: "backsvala", name: "Backsvala", order: 215 },
  { id: "ladusvala", name: "Ladusvala", order: 216 },
  { id: "hussvala", name: "Hussvala", order: 217 },
  { id: "rostgumpsvala", name: "Rostgumpsvala", order: 218 },
  { id: "stjartmes", name: "Stjärtmes", order: 219 },
  { id: "gronsangare", name: "Grönsångare", order: 220 },
  { id: "taigasangare", name: "Taigasångare", order: 221 },
  { id: "kungsfagelsangare", name: "Kungsfågelsångare", order: 222 },
  { id: "lovsangare", name: "Lövsångare", order: 223 },
  { id: "gransangare", name: "Gransångare", order: 224 },
  { id: "lundsangare", name: "Lundsångare", order: 225 },
  { id: "nordsangare", name: "Nordsångare", order: 226 },
  { id: "tradgardssangare", name: "Trädgårdssångare", order: 227 },
  { id: "svarthatta", name: "Svarthätta", order: 228 },
  { id: "hoksangare", name: "Höksångare", order: 229 },
  { id: "artsangare", name: "Ärtsångare", order: 230 },
  { id: "tornsangare", name: "Törnsångare", order: 231 },
  { id: "sidensvans", name: "Sidensvans", order: 232 },
  { id: "brandkronad-kungsfagel", name: "Brandkronad kungsfågel", order: 233 },
  { id: "kungsfagel", name: "Kungsfågel", order: 234 },
  { id: "notvacka", name: "Nötväcka", order: 235 },
  { id: "tradkrypare", name: "Trädkrypare", order: 236 },
  { id: "gardsmyg", name: "Gärdsmyg", order: 237 },
  { id: "stare", name: "Stare", order: 238 },
  { id: "stromstare", name: "Strömstare", order: 239 },
  { id: "dubbeltrast", name: "Dubbeltrast", order: 240 },
  { id: "taltrast", name: "Taltrast", order: 241 },
  { id: "rodvingetrast", name: "Rödvingetrast", order: 242 },
  { id: "koltrast", name: "Koltrast", order: 243 },
  { id: "bjorktrast", name: "Björktrast", order: 244 },
  { id: "ringtrast", name: "Ringtrast", order: 245 },
  { id: "gra-flugsnappare", name: "Grå flugsnappare", order: 246 },
  { id: "rodhake", name: "Rödhake", order: 247 },
  { id: "naktergal", name: "Näktergal", order: 248 },
  { id: "blahake", name: "Blåhake", order: 249 },
  { id: "mindre-flugsnappare", name: "Mindre flugsnappare", order: 250 },
  { id: "halsbandsflugsnappare", name: "Halsbandsflugsnappare", order: 251 },
  { id: "svartvit-flugsnappare", name: "Svartvit flugsnappare", order: 252 },
  { id: "svart-rodstjart", name: "Svart rödstjärt", order: 253 },
  { id: "rodstjart", name: "Rödstjärt", order: 254 },
  { id: "buskskvatta", name: "Buskskvätta", order: 255 },
  { id: "svarthakad-buskskvatta", name: "Svarthakad buskskvätta", order: 256 },
  { id: "stenskvatta", name: "Stenskvätta", order: 257 },
  { id: "jarnsparv", name: "Järnsparv", order: 258 },
  { id: "pilfink", name: "Pilfink", order: 259 },
  { id: "grasparv", name: "Gråsparv", order: 260 },
  { id: "forsarla", name: "Forsärla", order: 261 },
  { id: "gularla", name: "Gulärla", order: 262 },
  { id: "citronarla", name: "Citronärla", order: 263 },
  { id: "sadesarla", name: "Sädesärla", order: 264 },
  { id: "faltpiplarka", name: "Fältpiplärka", order: 265 },
  { id: "storre-piplarka", name: "Större piplärka", order: 266 },
  { id: "tradpiplarka", name: "Trädpiplärka", order: 267 },
  { id: "rodstrupig-piplarka", name: "Rödstrupig piplärka", order: 268 },
  { id: "angspiplarka", name: "Ängspiplärka", order: 269 },
  { id: "skarpiplarka", name: "Skärpiplärka", order: 270 },
  { id: "vattenpiplarka", name: "Vattenpiplärka", order: 271 },
  { id: "bergfink", name: "Bergfink", order: 272 },
  { id: "bofink", name: "Bofink", order: 273 },
  { id: "stenknack", name: "Stenknäck", order: 274 },
  { id: "rosenfink", name: "Rosenfink", order: 275 },
  { id: "tallbit", name: "Tallbit", order: 276 },
  { id: "domherre", name: "Domherre", order: 277 },
  { id: "gronfink", name: "Grönfink", order: 278 },
  { id: "vinterhampling", name: "Vinterhämpling", order: 279 },
  { id: "hampling", name: "Hämpling", order: 280 },
  { id: "grasiska", name: "Gråsiska", order: 281 },
  { id: "bandelkorsnabb", name: "Bändelkorsnäbb", order: 282 },
  { id: "storre-korsnabb", name: "Större korsnäbb", order: 283 },
  { id: "mindre-korsnabb", name: "Mindre korsnäbb", order: 284 },
  { id: "steglits", name: "Steglits", order: 285 },
  { id: "gulhampling", name: "Gulhämpling", order: 286 },
  { id: "gronsiska", name: "Grönsiska", order: 287 },
  { id: "snosparv", name: "Snösparv", order: 288 },
  { id: "lappsparv", name: "Lappsparv", order: 289 },
  { id: "savsparv", name: "Sävsparv", order: 290 },
  { id: "dvargsparv", name: "Dvärgsparv", order: 291 },
  { id: "videsparv", name: "Videsparv", order: 292 },
  { id: "kornsparv", name: "Kornsparv", order: 293 },
  { id: "ortolansparv", name: "Ortolansparv", order: 294 },
  { id: "gulsparv", name: "Gulsparv", order: 295 },
  { id: "mindre-strandpipare", name: "Mindre strandpipare", order: 296 },
  { id: "svartbent-strandpipare", name: "Svartbent strandpipare", order: 297 },
  { id: "gralira", name: "Grålira", order: 298 },
  { id: "snosiska", name: "Snösiska", order: 299 }
];
